name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push backend
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: backend/Dockerfile
          target: build
          tags: | 
            grchr/avpd-backend:main.${{github.sha}}
            grchr/avpd-backend:dev
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Test backend
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          file: backend/Dockerfile
          target: test
