name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Get GCloud Credentials
        id: gcloud
        uses: elgohr/gcloud-login-action@master
        with:
          account_key: ${{ secrets.GCLOUD_AUTH }}
      -
        name: Login to GCloud
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: ${{ steps.gcloud.outputs.username }}
          password: ${{ steps.gcloud.outputs.password }}
      -
        name: Build and push backend
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          file: backend/Dockerfile
          outputs: type=local
          target: build
          tags: | 
            gcr.io/team25-avpd/gchristensen/avpd-backend-dev
      -
        name: Deploy service to Cloud Run
        uses: stefda/action-cloud-run@v1.2
        with:
          image: gcr.io/team25-avpd/gchristensen/avpd-backend-dev
          service: avpd-backend-dev
          project: team25-avpd
          region: us-west1
          service key: ${{ secrets.GCLOUD_AUTH }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
