name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build-test-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and test
        id: docker_build_frontend
        uses: docker/build-push-action@v2
        with:
          load: true
          context: frontend/
          tags: |
            gcr.io/team25-avpd/gchristensen/avpd-frontend-dev
      -
        name: Deploy frontend to Cloud Run
        uses: stefda/action-cloud-run@v1.2
        with:
          image: gcr.io/team25-avpd/gchristensen/avpd-frontend-dev
          service: avpd-frontend-dev
          project: team25-avpd
          region: us-west1
          service key: ${{ secrets.GCLOUD_AUTH }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  build-test-deploy-backend:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Get GCloud Credentials
        id: gcloud
        uses: elgohr/gcloud-login-action@master
        with:
          account_key: ${{ secrets.GCLOUD_AUTH }}
      -
        name: Login to GCloud
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: ${{ steps.gcloud.outputs.username }}
          password: ${{ steps.gcloud.outputs.password }}
      -
        name: Build and test frontend
        id: docker_build_frontend
        uses: docker/build-push-action@v2
        with:
          load: true
          context: frontend
          tags: |
            gcr.io/team25-avpd/gchristensen/avpd-frontend-dev
      -
        name: Deploy frontend to Cloud Run
        uses: stefda/action-cloud-run@v1.2
        with:
          image: gcr.io/team25-avpd/gchristensen/avpd-frontend-dev
          service: avpd-frontend-dev
          project: team25-avpd
          region: us-west1
          service key: ${{ secrets.GCLOUD_AUTH }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
